[package]
name = "rinex"
version = "0.1.0"
license-file = "LICENSE"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "Package to parse and analyze RINEX data"
homepage = "https://github.com/gwbres/rinex"
keywords = ["rinex", "positionning", "timing", "gps"]
categories = ["science", "parsing"]
edition = "2018"
readme = "README.md"

exclude = ["data/",]

[build-dependencies]
serde_json = "1.0"

[dependencies]
chrono = "0.4"
thiserror = "1"
scan_fmt = "0.1"
lazy_static = "1"
rust-3d = "0.34.0"
strum = "0.23.0"
strum_macros = "0.23.0"
physical_constants = "0.4.1"
num-integer = "0.1.44"

[dev-dependencies]
itertools = "0.10.3"
