[package]
name = "rinex"
version = "0.0.9"
license-file = "LICENSE"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "Package to parse and analyze RINEX data"
homepage = "https://github.com/gwbres/rinex"
keywords = ["rinex", "positionning", "timing", "gps"]
categories = ["science", "parsing"]
edition = "2018"
readme = "README.md"

exclude = ["data/",]

[dependencies]
thiserror = "1"
rust-3d = "0.34.0"
chrono = "0.4"
scan_fmt = "0.1"
regex = "1"
