[package]
name = "rinex"
version = "0.0.2"
license-file = "LICENSE"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "Package to parse and analyze RINEX data"
homepage = "https://github.com/gwbres/rinex"
keywords = ["rinex", "positionning", "timing", "gps"]
edition = "2018"
readme = "README.md"

exclude = ["data/",]

[dependencies]
thiserror = "1"
chrono = "0.4"
scan_fmt = "0.1"
geo-types = "0.7.2"
regex = "1"
