name: benchmark

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update && sudo apt-get install libudev-dev libfontconfig1-dev
        cargo build --all-features --verbose
    - name: Benchmark (all features)
      run: cargo bench --all-features
